const { sequelize } = require('../../models');
const logger = require('../../config/logger');

async function ensureInstitutionalSchema() {
  try {
    await sequelize.query(`
      CREATE TABLE IF NOT EXISTS announcements (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
        author_id VARCHAR(36) NOT NULL REFERENCES users(id),
        title VARCHAR(255) NOT NULL,
        body TEXT NOT NULL,
        is_pinned BOOLEAN DEFAULT FALSE,
        link_url VARCHAR(500),
        attachment_name VARCHAR(255),
        attachment_path VARCHAR(500),
        publish_at TIMESTAMP,
        is_hidden BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
    await sequelize.query(`ALTER TABLE announcements ADD COLUMN IF NOT EXISTS link_url VARCHAR(500)`);
    await sequelize.query(`ALTER TABLE announcements ADD COLUMN IF NOT EXISTS attachment_name VARCHAR(255)`);
    await sequelize.query(`ALTER TABLE announcements ADD COLUMN IF NOT EXISTS attachment_path VARCHAR(500)`);
    await sequelize.query(`ALTER TABLE announcements ADD COLUMN IF NOT EXISTS publish_at TIMESTAMP`);
    await sequelize.query(`ALTER TABLE announcements ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE`);

    await sequelize.query(`ALTER TABLE discussions ADD COLUMN IF NOT EXISTS parent_id INTEGER REFERENCES discussions(id) ON DELETE CASCADE`);

    await sequelize.query(`CREATE INDEX IF NOT EXISTS idx_announcements_course_id ON announcements(course_id)`);
    await sequelize.query(`CREATE INDEX IF NOT EXISTS idx_discussions_parent_id ON discussions(parent_id)`);

    await sequelize.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS idx_quiz_attempt_one_in_progress
      ON quiz_attempts (quiz_id, student_id)
      WHERE submitted_at IS NULL
    `).catch(() => {});

    logger.info('Institutional schema ready (announcements, discussions)');
  } catch (err) {
    logger.warn(`Institutional schema ensure skipped: ${err.message}`);
  }
}

module.exports = { ensureInstitutionalSchema };
