const { sequelize } = require('../../models');
const logger = require('../../config/logger');

async function ensureLiveClassSchema() {
  try {
    await sequelize.query(`
      CREATE TABLE IF NOT EXISTS live_class_sessions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        room_id INTEGER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
        course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
        started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ended_at TIMESTAMP,
        summary_json TEXT
      )
    `);

    await sequelize.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS live_class_sessions_one_open_per_room
      ON live_class_sessions (room_id)
      WHERE ended_at IS NULL
    `);

    await sequelize.query(`
      CREATE TABLE IF NOT EXISTS live_class_attendance (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id INTEGER NOT NULL REFERENCES live_class_sessions(id) ON DELETE CASCADE,
        user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        role VARCHAR(20) NOT NULL,
        enrollment_id INTEGER REFERENCES enrollments(id) ON DELETE SET NULL,
        first_joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_ping_at TIMESTAMP,
        last_left_at TIMESTAMP,
        cumulative_seconds INTEGER NOT NULL DEFAULT 0,
        participation_json TEXT,
        computed_status VARCHAR(40)
      )
    `);

    await sequelize.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS live_class_attendance_session_user
      ON live_class_attendance (session_id, user_id)
    `);

    await sequelize.query(`
      CREATE INDEX IF NOT EXISTS live_class_attendance_session_idx
      ON live_class_attendance (session_id)
    `);

    logger.info('Live class schema ready (sessions, attendance)');
  } catch (err) {
    logger.warn(`Live class schema ensure skipped: ${err.message}`);
  }
}

module.exports = { ensureLiveClassSchema };
