const { sequelize } = require('../../models');
const logger = require('../../config/logger');

async function ensureCourseModulesSchema() {
  try {
    await sequelize.query(`
      CREATE TABLE IF NOT EXISTS course_modules (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        sort_order INTEGER DEFAULT 0,
        is_published BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await sequelize.query(`
      CREATE TABLE IF NOT EXISTS course_module_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        module_id INTEGER NOT NULL REFERENCES course_modules(id) ON DELETE CASCADE,
        item_type VARCHAR(32) NOT NULL,
        title VARCHAR(255) NOT NULL,
        link_url VARCHAR(500),
        sort_order INTEGER DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    const resourceTables = ['materials', 'assignments', 'quizzes', 'exams'];
    for (const table of resourceTables) {
      await sequelize.query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS module_id INTEGER REFERENCES course_modules(id) ON DELETE SET NULL`);
      await sequelize.query(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS module_sort_order INTEGER DEFAULT 0`);
      await sequelize.query(`CREATE INDEX IF NOT EXISTS idx_${table}_module_id ON ${table}(module_id)`);
    }

    await sequelize.query('CREATE INDEX IF NOT EXISTS idx_course_modules_course_id ON course_modules(course_id)');
    await sequelize.query('CREATE INDEX IF NOT EXISTS idx_course_module_items_module_id ON course_module_items(module_id)');

    logger.info('Course modules schema ready');
  } catch (err) {
    logger.warn(`Course modules schema ensure skipped: ${err.message}`);
  }
}

module.exports = { ensureCourseModulesSchema };
