CREATE TABLE IF NOT EXISTS enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  student_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_enrollment UNIQUE (course_id, student_id)
);

ALTER TABLE enrollments
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_name = 'enrollments'
      AND constraint_name = 'enrollments_course_id_fkey'
  ) THEN
    ALTER TABLE enrollments DROP CONSTRAINT enrollments_course_id_fkey;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_name = 'enrollments'
      AND constraint_name = 'enrollments_student_id_fkey'
  ) THEN
    ALTER TABLE enrollments DROP CONSTRAINT enrollments_student_id_fkey;
  END IF;
END $$;

ALTER TABLE enrollments
  ADD CONSTRAINT enrollments_course_id_fkey
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  ADD CONSTRAINT enrollments_student_id_fkey
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE;
