ALTER TABLE assignments
  ADD COLUMN IF NOT EXISTS file_path VARCHAR(500),
  ADD COLUMN IF NOT EXISTS file_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS file_type VARCHAR(100),
  ADD COLUMN IF NOT EXISTS is_encrypted BOOLEAN DEFAULT FALSE;
