CREATE TABLE IF NOT EXISTS calendar_custom_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  author_id VARCHAR(36) NOT NULL REFERENCES users(id),
  event_type VARCHAR(32) NOT NULL DEFAULT 'office_hours',
  title VARCHAR(255) NOT NULL,
  description TEXT,
  starts_at TIMESTAMP NOT NULL,
  ends_at TIMESTAMP,
  is_published BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_calendar_custom_events_course ON calendar_custom_events(course_id);
CREATE INDEX IF NOT EXISTS idx_calendar_custom_events_starts ON calendar_custom_events(starts_at);
