-- Student exam access tracking (download during window = completion)
CREATE TABLE IF NOT EXISTS exam_student_access (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id INTEGER NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  student_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (exam_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_exam_student_access_exam ON exam_student_access(exam_id);
