-- SBLE PostgreSQL Database Schema
-- Run with: psql -U postgres -d sble -f init.sql

BEGIN;

DROP TABLE IF EXISTS audit_logs, discussions, rooms, exams, quiz_attempts, quiz_questions, quizzes, submissions, assignments, materials, enrollments, courses, users CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS submission_type CASCADE;
DROP TYPE IF EXISTS question_type CASCADE;

CREATE TYPE user_role AS ENUM ('student', 'lecturer', 'admin');
CREATE TYPE submission_type AS ENUM ('typed', 'scanned', 'handwritten');
CREATE TYPE question_type AS ENUM ('mcq', 'true_false', 'short_answer');

-- Users (synced from Keycloak)
CREATE TABLE users (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  full_name VARCHAR(255) NOT NULL,
  role user_role NOT NULL DEFAULT 'student',
  student_id VARCHAR(50) UNIQUE,
  program VARCHAR(255),
  year_of_study INTEGER,
  semester INTEGER,
  mode VARCHAR(20),
  institution VARCHAR(255),
  staff_email VARCHAR(255) UNIQUE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Courses
CREATE TABLE courses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  lecturer_id VARCHAR(36) NOT NULL REFERENCES users(id),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Course enrollments
CREATE TABLE enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  student_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_enrollment UNIQUE (course_id, student_id)
);

-- Course discussions
CREATE TABLE discussions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id),
  user_id VARCHAR(36) NOT NULL REFERENCES users(id),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Learning materials (encrypted files)
CREATE TABLE materials (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id),
  title VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(100),
  is_encrypted BOOLEAN DEFAULT TRUE,
  uploaded_by VARCHAR(36) NOT NULL REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Assignments
CREATE TABLE assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  file_path VARCHAR(500),
  file_name VARCHAR(255),
  file_type VARCHAR(100),
  is_encrypted BOOLEAN DEFAULT FALSE,
  due_date TIMESTAMP,
  allows_handwritten BOOLEAN DEFAULT TRUE,
  created_by VARCHAR(36) NOT NULL REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Assignment submissions
CREATE TABLE submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id INTEGER NOT NULL REFERENCES assignments(id),
  student_id VARCHAR(36) NOT NULL REFERENCES users(id),
  file_path VARCHAR(500),
  file_name VARCHAR(255),
  submission_type submission_type DEFAULT 'typed',
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  last_updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  grade NUMERIC(5,2),
  feedback TEXT
);

-- Quizzes
CREATE TABLE quizzes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id),
  title VARCHAR(255) NOT NULL,
  time_limit_minutes INTEGER DEFAULT 30,
  is_published BOOLEAN DEFAULT FALSE,
  created_by VARCHAR(36) NOT NULL REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Quiz questions
CREATE TABLE quiz_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id INTEGER NOT NULL REFERENCES quizzes(id),
  question_text TEXT NOT NULL,
  question_type question_type NOT NULL,
  options JSONB,
  correct_answer TEXT,
  marks INTEGER DEFAULT 1
);

-- Quiz attempts
CREATE TABLE quiz_attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id INTEGER NOT NULL REFERENCES quizzes(id),
  student_id VARCHAR(36) NOT NULL REFERENCES users(id),
  answers JSONB,
  score NUMERIC(5,2),
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMP
);

-- Exams
CREATE TABLE exams (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id),
  title VARCHAR(255) NOT NULL,
  file_path VARCHAR(500),
  scheduled_at TIMESTAMP,
  duration_minutes INTEGER DEFAULT 120,
  is_released BOOLEAN DEFAULT FALSE,
  created_by VARCHAR(36) NOT NULL REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Collaboration rooms
CREATE TABLE rooms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id),
  title VARCHAR(255) NOT NULL,
  room_token VARCHAR(255) UNIQUE NOT NULL,
  created_by VARCHAR(36) NOT NULL REFERENCES users(id),
  is_active BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Audit log for security tracking
CREATE TABLE audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(36),
  action VARCHAR(255) NOT NULL,
  resource_type VARCHAR(100),
  resource_id VARCHAR(100),
  ip_address VARCHAR(45),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
